# Spring Configuration
spring:
  application:
    name: analytics
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mujiki_analytics
    username: mujiki_analytics
    password: nothing

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  # Spring Cloud Stream - Kafka Configuration
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092  # Kafka broker location, can be a list for multiple brokers
        streams:
          bindings:
            handleFeedbackEvent-in-0:
              consumer:
                application-id: mujikiAnalyticsFeedbackApplication
            handleOrderStatusEvent-in-0:
              consumer:
                application-id: mujikiAnalyticsOrderApplication
      bindings:
        handleFeedbackEvent-in-0:
          destination: mujikiFeedbackEvent  # Topic for Mujiki Feedback Events
          content-type: application/json    # Content type for messages
        handleOrderStatusEvent-in-0:
          destination: mujikiOrderEvent     # Topic for Mujiki Order Events
          content-type: application/json    # Content type for messages
    function:
      definition: handleFeedbackEvent;handleOrderStatusEvent

# API Configuration
api:
  endpoint:
    base-url: /api

# Server Configuration
server:
  error:
    whitelabel:
      enabled: false
  port: 8089

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
#          event: DEBUG
        context: DEBUG
